name: EasyElevator
main: dzjkb.EasyElevator.EasyElevator
version: 8.3
api-version: 1.14
commands:
  elv:
    description: Elevator Commands
    usage: /elv
  eelevator:
    description: Elevator Commands
    usage: /eelevator